# .github/workflows/main.yml

# 工作流的名称
name: Generate Question Bank Manifest

# 触发条件：当有代码被推送到 main 或 master 分支时自动运行
on:
  push:
    branches:
      - main
      - master

# 定义具体的工作任务
jobs:
  build:
    # 运行此任务的虚拟机环境
    runs-on: ubuntu-latest

    # 新增：为机器人授予写入仓库的权限
    permissions:
      contents: write

    # 任务步骤
    steps:
      # 步骤1：将你的仓库代码下载到虚拟机中
      - name: Checkout repository
        uses: actions/checkout@v3

      # 步骤2：设置 Node.js 环境，我们使用 16.x 版本
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 步骤3：运行我们之前编写的自动化脚本
      - name: Generate manifest file
        run: node generateManifest.js

      # 步骤4：检查是否有文件变动（即 manifest.json 是否被更新）
      # 并将变动提交回你的 GitHub 仓库
      - name: Commit and push if changed
        run: |
          # 配置 Git 的用户名和邮箱
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # 将所有变动（主要是 manifest.json）添加到暂存区
          git add .
          
          # 检查暂存区是否有变动
          # "git diff --staged --quiet" 如果没有变动，会退出码为0；有变动则为1
          # "||" 符号表示如果前一个命令失败（即有变动），则执行后面的命令
          git diff --staged --quiet || (
            git commit -m "docs: auto-generate manifest.json" &&
            git push
          )
